### PR TITLE
TEST/IODEMO: close the ep if the err_cb was called before conn_id is set

### PR DESCRIPTION
**Pull request by alinask**

### CODE REVIEW

**Comment by alinask** [comment]
@yosefe @evgeny-leksikov can you please review?

**Comment by alinask** [comment]
actually, is this solution safe enough? what if the err_cb is called right after this new check but before _remote_conn_id was set

**Review by yosefe — APPROVED** [review]

**Comment by yosefe** [comment]
> actually, is this solution safe enough? what if the err_cb is called right after this new check but before _remote_conn_id was set

from which thread?

**Comment by alinask** [comment]
> > actually, is this solution safe enough? what if the err_cb is called right after this new check but before _remote_conn_id was set
> 
> from which thread?

actually, the err_cb is called only from the main thread so it's fine.
ok then.

**Review by evgeny-leksikov — APPROVED** [review]

**Pull request merged**
