### PR TITLE
IODEMO: remove unused variable

### PR DESCRIPTION
**Pull request by evgeny-leksikov**
found by clang

### CODE REVIEW

**Comment by yosefe** [comment]
@evgeny-leksikov can you pls rebase?

**Review by yosefe — APPROVED** [review]

**Comment by evgeny-leksikov** [comment]
@yosefe maybe we could add `-Wextra` to GCC flags in master, WDYT?

**Comment by yosefe** [comment]
> @yosefe maybe we could add `-Wextra` to GCC flags in master, WDYT?

And fix new warnings which will arise?

**Comment by evgeny-leksikov** [comment]
> > @yosefe maybe we could add `-Wextra` to GCC flags in master, WDYT?
> 
> And fix new warnings which will arise?

I guess we should not have too much since we have clang, coverity, etc in CI but if something is missed and it could improve code - why not? :)

**Comment by yosefe** [comment]
> I guess we should not have too much since we have clang, coverity, etc in CI but if something is missed and it could improve code - why not? :)

Ok, sounds good

**Pull request merged**
